### ISSUE TITLE
[feat] 포스트 작성 기능

### ISSUE THREAD

**Issue by Hyun-bin-Kim** [prgrms-fe-devcourse/NFE1_2_2_MUX#14]
## 🛠️ 만들고자 하는 기능
- 사용자가 음악에 대한 추천 포스트를 작성할 수 있는 포스트 업로드 기능

## 📝 구현 내용
- [x] 사용자가 업로드하는 음악에 대한 추천 문구를 작성할 수 있는 텍스트 입력란 구현
- [x] 문구 텍스트는 최대 300자 제한, 사용자가 텍스트 작성 시 실시간으로 글자 수 표시
- [x] 텍스트 입력란 내에 사용자가 작성할 수 있는 추천 문구에 대한 예시 or 가이드 텍스트 구현
- [x] 사용자가 업로드하는 음악에 대한 추천 포스트 제목 입력란 기능 구현 
- [x] 제목 텍스트는 최대 20자 제한, 사용자가 텍스트 작성 시 실시간으로 글자 수 표시
- [x] 사용자가 유튜브뮤직api를 이용하여 검색을 통해 앨범의 이미지 및 곡 정보를 가져올 수 있는 기능 구현
- [x] 앨범 등록 이후 앨범 부분 선택 시 재 검색 기능 구현
- [x] 곡을 미리 재생해볼 수 있는 재생 바 구현
- [x] 포스트 작성이 완료되면 게시할 수 있는 "게시" 버튼 구현
- [x] 게시할 때 부모 컴포넌트로 이동 및 유효성 검사 기능 구현

## 🗓️ 개발 일정
09월 27일 ~ 09월 29일

**Comment by hjlee2778** [comment]
현빈님 저 테스트 하다가 발견한건데

1. 제목이 20자가 넘어가도 글이 게시가 됨.
2. 앨범을 하나도 선택 안해도 글이 게시가 됨. 

이거 한 번 확인해 보셔야 할 것 같습니다!
