### ISSUE TITLE
[feat] curation-artist 페이지 구현

### ISSUE THREAD

**Issue by Hyun-bin-Kim** [prgrms-fe-devcourse/NFE1_2_2_MUX#17]
## 🛠️ 만들고자 하는 기능
- 아티스트, 큐레이션 리스트를 나열하는 페이지 구현

## 📝 구현 내용
- [x] CurationTrackList
- [x] ArtistTrackList

## 🗓️ 개발 일정
10월 01일 ~ 10월 02일

**Comment by hjlee2778** [comment]
현빈님 혹시 헷갈리실 수도 있어서 말씀드리는 건데, 아티스트 트랙에 있는 세로로 길쭉한 카드는 공통 컴포넌트 아니어서 현빈님이 구성해주셔야 합니다!
